### ISSUE TITLE
CException

### ISSUE THREAD

**Issue by raphsilvab** [ufrgs/spell#1]
Subi no servidor APACHE e, me apresenta este erro:

"O caminho "C:\xampp\htdocs\ponto\ponto\protected\runtime" da Application runtime não é válido. Por favor, tenha certeza que é um diretório que o servidor Web possa escrever nele."

Há alguma maneira de resolver?

Grato.

**Comment by tsmotta** [comment]
Olá! Sim, basta criar um diretório chamado "runtime" abaixo do diretório protected e dar permissão de escrita para a aplicação.
