### ISSUE TITLE
syntax error, unexpected end of file

### ISSUE THREAD

**Issue by mateusscheper** [ufrgs/spell#2]
Olá!

Estou tentando instalar o sistema para testes e estou tendo um probleminha.
Ao acessar localhost/ponto, o sistema retorna o erro "PHP Parse error:  syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in /var/www/html/ponto/protected/views/layouts/main.php on line 58".
Além do problema acima, a URL /tempLogin/login parece não existir.

Poderia dar um auxílio, por gentileza?

- Estou utilizando o servidor apache com PHP 7.2 e MySQL 5.7.
- O projeto está em /var/www/html/ponto, e o yii está em /var/www/html/yii.
- O script do banco rodou sem problemas.

Obrigado desde já!

**Comment by tsmotta** [comment]
Oi, Mateus!

Acredito que seja só questão de habilitar as short_tags no php.ini.

Abraço,
Thiago

Em seg., 17 de mai. de 2021 às 13:32, mateusscheper <
***@***.***> escreveu:

**Comment by mateusscheper** [comment]
> Oi, Mateus! Acredito que seja só questão de habilitar as short_tags no php.ini. 

Deu certo! Muito obrigado pela resposta.

Infelizmente caí em outro erro:
`session_name(): Cannot change session name when session is active`
O erro acontece ao acessar http://localhost/ponto/.
Sobre a URL, também não consigo acessar, dando 404: http://localhost/tempLogin/login. 
Sabe o que pode ser?

**Comment by tsmotta** [comment]
Que bom que era isso e que ruim que deu um erro diferente... hehe
O primeiro erro, de sessão, não sei o que pode ser. Nunca vi.
O segundo erro, de não conseguir acessar, pode ser configuração do
servidor, que não está lendo o arquivo .htaccess. De qualquer forma, está
faltando um "/ponto" ali. Tenta acessar por
http://localhost/ponto/tempLogin/login ou
http://localhost/ponto/index.php/tempLogin/login

Abraço,
Thiago

Em seg., 17 de mai. de 2021 às 16:48, mateusscheper <
***@***.***> escreveu:
